version: 2

registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.READER_TOKEN }}

updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
      time: '03:00'
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '03:00'
    open-pull-requests-limit: 20
    registries: '*'
    ignore:
      - dependency-name: '@types/node'
      - dependency-name: 'eslint'
        versions: ['9.x']
